// Code generated by go-swagger; DO NOT EDIT.

package single_key_operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateKeyHandlerFunc turns a function with the right signature into a create key handler
type CreateKeyHandlerFunc func(CreateKeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateKeyHandlerFunc) Handle(params CreateKeyParams) middleware.Responder {
	return fn(params)
}

// CreateKeyHandler interface for that can handle valid create key params
type CreateKeyHandler interface {
	Handle(CreateKeyParams) middleware.Responder
}

// NewCreateKey creates a new http.Handler for the create key operation
func NewCreateKey(ctx *middleware.Context, handler CreateKeyHandler) *CreateKey {
	return &CreateKey{Context: ctx, Handler: handler}
}

/* CreateKey swagger:route POST /create single key operation createKey

Return a new key

*/
type CreateKey struct {
	Context *middleware.Context
	Handler CreateKeyHandler
}

func (o *CreateKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateKeyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
