// Code generated by go-swagger; DO NOT EDIT.

package single_key_operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"keyserver/models"
)

// CreateKeyOKCode is the HTTP code returned for type CreateKeyOK
const CreateKeyOKCode int = 200

/*CreateKeyOK OK

swagger:response createKeyOK
*/
type CreateKeyOK struct {

	/*
	  In: Body
	*/
	Payload []*models.KeyData `json:"body,omitempty"`
}

// NewCreateKeyOK creates CreateKeyOK with default headers values
func NewCreateKeyOK() *CreateKeyOK {

	return &CreateKeyOK{}
}

// WithPayload adds the payload to the create key o k response
func (o *CreateKeyOK) WithPayload(payload []*models.KeyData) *CreateKeyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create key o k response
func (o *CreateKeyOK) SetPayload(payload []*models.KeyData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.KeyData, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateKeyMethodNotAllowedCode is the HTTP code returned for type CreateKeyMethodNotAllowed
const CreateKeyMethodNotAllowedCode int = 405

/*CreateKeyMethodNotAllowed Invalid input

swagger:response createKeyMethodNotAllowed
*/
type CreateKeyMethodNotAllowed struct {
}

// NewCreateKeyMethodNotAllowed creates CreateKeyMethodNotAllowed with default headers values
func NewCreateKeyMethodNotAllowed() *CreateKeyMethodNotAllowed {

	return &CreateKeyMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateKeyMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// CreateKeyInternalServerErrorCode is the HTTP code returned for type CreateKeyInternalServerError
const CreateKeyInternalServerErrorCode int = 500

/*CreateKeyInternalServerError Internal server error

swagger:response createKeyInternalServerError
*/
type CreateKeyInternalServerError struct {
}

// NewCreateKeyInternalServerError creates CreateKeyInternalServerError with default headers values
func NewCreateKeyInternalServerError() *CreateKeyInternalServerError {

	return &CreateKeyInternalServerError{}
}

// WriteResponse to the client
func (o *CreateKeyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
