// Code generated by go-swagger; DO NOT EDIT.

package single_key_operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"keyserver/models"
)

// KeyGetOKCode is the HTTP code returned for type KeyGetOK
const KeyGetOKCode int = 200

/*KeyGetOK OK

swagger:response keyGetOK
*/
type KeyGetOK struct {

	/*
	  In: Body
	*/
	Payload []*models.KeyData `json:"body,omitempty"`
}

// NewKeyGetOK creates KeyGetOK with default headers values
func NewKeyGetOK() *KeyGetOK {

	return &KeyGetOK{}
}

// WithPayload adds the payload to the key get o k response
func (o *KeyGetOK) WithPayload(payload []*models.KeyData) *KeyGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the key get o k response
func (o *KeyGetOK) SetPayload(payload []*models.KeyData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KeyGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.KeyData, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// KeyGetNotFoundCode is the HTTP code returned for type KeyGetNotFound
const KeyGetNotFoundCode int = 404

/*KeyGetNotFound No key was found

swagger:response keyGetNotFound
*/
type KeyGetNotFound struct {
}

// NewKeyGetNotFound creates KeyGetNotFound with default headers values
func NewKeyGetNotFound() *KeyGetNotFound {

	return &KeyGetNotFound{}
}

// WriteResponse to the client
func (o *KeyGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// KeyGetInternalServerErrorCode is the HTTP code returned for type KeyGetInternalServerError
const KeyGetInternalServerErrorCode int = 500

/*KeyGetInternalServerError Internal server error

swagger:response keyGetInternalServerError
*/
type KeyGetInternalServerError struct {
}

// NewKeyGetInternalServerError creates KeyGetInternalServerError with default headers values
func NewKeyGetInternalServerError() *KeyGetInternalServerError {

	return &KeyGetInternalServerError{}
}

// WriteResponse to the client
func (o *KeyGetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
